### ISSUE TITLE
[Bug]: Builds are broken on Windows due to Unix-specific import

### ISSUE THREAD

**Issue by juv** [rapina-rs/rapina#305]
### Description

Windows builds were broken after the graceful shutdown feature was introduced in #233. 

### Steps to Reproduce

Run build on Windows

### Expected Behavior

Build is successful on Windows

### Code Example

```rust

```

### Environment

- OS: Windows

### Error Output / Logs

```shell
error[E0432]: unresolved import `tokio::signal::unix`
  --> rapina\src\server.rs:14:20
   |
14 | use tokio::signal::unix::SignalKind;
   |                    ^^^^ could not find `unix` in `signal`
   |
note: found an item that was configured out
  --> C:\Users\juv\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.49.0\src\signal\mod.rs:63:9
   |
63 | pub mod unix;
   |         ^^^^
   |
  ::: C:\Users\juv\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tokio-1.49.0\src\signal\unix.rs:6:8
   |
 6 | #![cfg(unix)]
   |        ---- the item is gated here
```
